#!/bin/bash
# Author: Andrew Oatley-Willis
# Description: ssh into a virsh managed vm using the vm name
# Usage: virsh-ssh [hostname/username@hostname]
# Instructions: place all the virsh-* scripts into /usr/local/bin/ on the c7host

# Uncomment below for sudo method
if [ "$(sudo whoami)" != "root" ]; then
  echo "Please run as root! or with sudo"
  exit 1
fi

# Uncomment below for root only
#if [ "$(whoami)" != "root" ]; then
#  echo "Please run as root!"
#  exit 1
#fi


# Check if correct number of arguments
if [ $# -ne 1 ]; then
  echo "Description: ssh into a virsh managed vm using the vm name" 
  echo "Usage: $0 [hostname/username@hostname]"
  exit 1
fi

# Check if the user entered hostname or username@hostname
HOSTNAME="$1"
USERNAME="$(whoami)"
if echo "$1" | grep "@"; then
  USERNAME=$(echo "$1" | awk -F"@" '{print $1}')
  HOSTNAME=$(echo "$1" | awk -F"@" '{print $2}')
fi

# Check if vm name exists before connecting
if ! virsh-ip ${HOSTNAME} 2>&1 > /dev/null ; then
  echo "Usage: $0 [hostname]"
  echo "VM not found or turned off"
  exit 1
fi

IPADDRESS=$(virsh-ip ${HOSTNAME} | awk -F":" '{print $2}')

echo "Running Command: ssh ${USERNAME}@${IPADDRESS}"

ssh ${USERNAME}@${IPADDRESS}
